### ISSUE TITLE
Bug: Double clicking a piece

### ISSUE THREAD

**Issue by ching23** [Devamp/StrategoFramework#13]
If the user double clicks on a piece, then single clicks on an open spot to move, the piece doesn’t move. This goes for when the user wants to select a different piece too (user double clicks a piece, single clicks an open spot, then single clicks a new piece). The game doesn’t register the single-clicked open spot or new piece. The user must double click their selected piece again then single click the open spot in order to move. Or double click the new piece to select that piece. Sometimes the double click doesn’t work, so the user would have to triple click. It’s hard for the user to keep track of the number of clicks they’ve done.

**Comment by devamp** [comment]
Thanks for pointing out this bug. I think it was being caused because the user was clicking on the image button multiple times and it wasn't clear if the button was pressed or not. We fixed this by adding a green highlight around each image button that is selected. So now you can easily tell if any buttons are pressed or not. This prevents all of the buggy behavior with pieces not being moved and such.
