### ISSUE TITLE
Bug: Computer Player doesn't move

### ISSUE THREAD

**Issue by uyeno24** [Devamp/StrategoFramework#14]
If the user plays their pieces to where the computer player does have an open spot to go to (the only move possible is to attack another piece) the computer player will not make a move. So the user can't finish the game.

**Comment by devamp** [comment]
Thanks for pointing this out. We've fixed this bug as now the dumb computer has a 50/50 chance of attacking or moving. It will attack if there is an enemy piece next to it, or else it will move a random piece. This bug was being caused because the computer wasn't attacking at all before. It is fixed not though.
